#!/bin/bash
svn export https://github.com/antonmalko/SLCLADAL.github.io/trunk/content ~/content
cp -r ~/content ~/originals
rm -f ~/renv.lock ~/runtime.txt ~/.Rhistory ~/postBuild ~/.gitignore ~/apt.txt

echo "setwd('~/content')" >> ~/.Rprofile
echo "setHook('rstudio.sessionInit', function(newSession) {" >> ~/.Rprofile
echo "if (newSession)" >> ~/.Rprofile
echo "rstudioapi::filesPaneNavigate(getwd())" >> ~/.Rprofile
echo "}, action = 'append')" >> ~/.Rprofile