#!/bin/bash
svn export https://github.com/antonmalko/SLCLADAL.github.io/trunk/content ~/content
cp -r ~/content ~/originals

echo "setwd('~/content')" >> ~/.Rprofile
echo "setHook('rstudio.sessionInit', function(newSession) {" >> ~/.Rprofile
echo "if (newSession)" >> ~/.Rprofile
echo "rstudioapi::filesPaneNavigate('~/content')" >> ~/.Rprofile
echo "}, action = 'append')" >> ~/.Rprofile

exec "$@"