# This is a basic workflow to help you get started with Actions

name: sync_renv

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync_renv:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Push posts
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.SYNC_REPOS }}
        with:
          source_file: 'renv.lock' # Folder to copy
          destination_repo: 'antonmalko/binder-env-test' # Target repo
          user_name: 'antonmalko'
          user_email: 'test@gmail.com'
          commit_message: "AUTO: syncing renv.lock on change"
          git_server: 'github.com'
